Bytter over til jq for å gjøre håndteringen av JSON bedre Legger til litt bedre logging samt kommentarer for å gjøre ting mer oversiktelig.

diff --git a/.github/actions/commitFiles/action.yml b/.github/actions/commitFiles/action.yml
--- a/.github/actions/commitFiles/action.yml
+++ b/.github/actions/commitFiles/action.yml
@@ -23,51 +23,55 @@ runs:
         printf -v bold '\033[1m'
         printf -v reset '\033[0m'
 
+        # Split the files into an array
         IFS=',' read -ra FILES <<< "$FILES"
 
+        # Check if the file paths contain commas
+        for file in "${FILES[@]}"; do
+          if [[ "$file" == *","* ]]; then
+            echo "::error::File paths should not contain commas. Found in: $file"
+            exit 1
+          fi
+        done
+
         echo "::group::Commit files"
+        echo "Files to commit: ${FILES[@]}"
+        echo "Commit message: $COMMIT_MESSAGE"
+
+        # Check if there are files to commit
         if [ ${#FILES[@]} -gt 0 ]; then
           # Prepare the JSON payload
-          JSON_PAYLOAD=$(cat <<EOF
-          {
-            "query": "$(cat .github/api/createCommitOnBranch.gql)",
-            "variables": {
-              "githubRepository": "${REPOSITORY}",
-              "branchName": "${REF_NAME}",
-              "expectedHeadOid": "$(git rev-parse HEAD)",
-              "commitMessage": "${COMMIT_MESSAGE}",
-              "files": [
-          EOF
-          )
+          if ! JSON_PAYLOAD=$(jq -n \
+          --arg query "$(cat .github/api/createCommitOnBranch.gql)" \
+          --arg repo "$REPOSITORY" \
+          --arg branch "$REF_NAME" \
+          --arg head "$(git rev-parse HEAD)" \
+          --arg message "$COMMIT_MESSAGE" \
+          '{query: $query, variables: {githubRepository: $repo, branchName: $branch, expectedHeadOid: $head, commitMessage: $message, files: []}}'); then
+            echo "::error::Failed to prepare JSON payload."
+            exit 1
+          fi
 
-          FILES_ARRAY=""
+          # Add the files to the JSON payload
+          FILES_ARRAY=$(jq -n)
           for file in "${FILES[@]}"; do
             if [ -f "$file" ] && [ -r "$file" ]; then
-              echo "${green}Adding file $file${reset}"
               base64_content=$(base64 -w0 "$file")
-              FILES_ARRAY+="{\"path\": \"$file\", \"contents\": \"$base64_content\"},"
+              FILES_ARRAY=$(echo "$FILES_ARRAY" | jq --arg path "$file" --arg content "$base64_content" '. + [{"path": $path, "contents": $content}]')
+              echo "${green}Adding $file to commit.${reset}"
             else
               echo "${red}File $file does not exist, skipping.${reset}"
+              echo "::warning ::${red}File $file does not exist, skipping.${reset}"
             fi
           done
 
-          # Remove the last comma if there are files
-          if [ -n "$FILES_ARRAY" ]; then
-            FILES_ARRAY=${FILES_ARRAY::-1} # Remove trailing comma
-          fi
-
-          JSON_PAYLOAD+=$(cat <<EOF
-          $FILES_ARRAY
-              ]
-            }
-          }
-          EOF
-          )
+          # Add the files array to the JSON payload
+          JSON_PAYLOAD=$(echo "$JSON_PAYLOAD" | jq --argjson files "$FILES_ARRAY" '.variables.files |= $files')
 
           echo "${green}${bold}Executing GraphQL query via curl:${reset} ${yellow}curl -X POST -H 'Authorization: bearer ***' -H 'Content-Type: application/json' -d '$JSON_PAYLOAD' https://api.github.com/graphql${reset}"
 
           # Actually execute the curl command
-          if ! curl_output=$(curl -X POST \
+          if ! curl_output=$(curl --silent --show-error -X POST \
             -H 'Authorization: bearer ${GH_TOKEN}' \
             -H 'Content-Type: application/json' \
             -d "$JSON_PAYLOAD" \
@@ -78,7 +82,7 @@ runs:
 
           echo "GitHub API response: $curl_output"
         else
-          echo "No files to commit."
+          echo "::warning::No files to commit."
         fi
         echo "::endgroup::"
       env:
