fix: Oppdatering for å se om vi får løst problem med at commits feiler

diff --git a/.github/actions/commitFiles/action.yml b/.github/actions/commitFiles/action.yml
--- a/.github/actions/commitFiles/action.yml
+++ b/.github/actions/commitFiles/action.yml
@@ -23,75 +23,67 @@ runs:
         printf -v bold '\033[1m'
         printf -v reset '\033[0m'
 
-        # Split the files into an array
+        # Split the input string into an array of file paths
         IFS=',' read -ra FILES <<< "$FILES"
 
-        # Check if the file paths contain commas
-        for file in "${FILES[@]}"; do
-          if [[ "$file" == *","* ]]; then
-            echo "::error::File paths should not contain commas. Found in: $file"
-            exit 1
-          fi
-        done
-
         echo "::group::Commit files"
-        echo "Files to commit: ${FILES[@]}"
-        echo "Commit message: $COMMIT_MESSAGE"
+        echo "${yellow}${bold}Files to commit:${reset} ${FILES[@]}"
+        echo "${yellow}${bold}Commit message:${reset} $COMMIT_MESSAGE"
 
-        # Check if there are files to commit
+        # Check if the files exist and are readable then try to commit them
         if [ ${#FILES[@]} -gt 0 ]; then
           # Prepare the JSON payload
           if ! JSON_PAYLOAD=$(jq -n \
-          --arg query "$(cat .github/api/createCommitOnBranch.gql)" \
-          --arg repo "$REPOSITORY" \
-          --arg branch "$REF_NAME" \
-          --arg head "$(git rev-parse HEAD)" \
-          --arg message "$COMMIT_MESSAGE" \
-          '{query: $query, variables: {githubRepository: $repo, branchName: $branch, expectedHeadOid: $head, commitMessage: $message, files: []}}'); then
+            --arg query "$(cat .github/api/createCommitOnBranch.gql)" \
+            --arg repo "$REPOSITORY" \
+            --arg branch "$REF_NAME" \
+            --arg head "$(git rev-parse HEAD)" \
+            --arg message "$COMMIT_MESSAGE" \
+            '{query: $query, variables: {githubRepository: $repo, branchName: $branch, expectedHeadOid: $head, commitMessage: $message, files: []}}'); then
             echo "::error::Failed to prepare JSON payload."
             exit 1
           fi
 
-          # Add the files to the JSON payload
+          # Prepare the array of files to commit
           FILES_ARRAY=$(jq -n)
+
+          # Loop through the files and add them to the JSON payload
           for file in "${FILES[@]}"; do
+            # Check if the file exists and is readable
             if [ -f "$file" ] && [ -r "$file" ]; then
               base64_content=$(base64 -w0 "$file")
               FILES_ARRAY=$(echo "$FILES_ARRAY" | jq --arg path "$file" --arg content "$base64_content" '. + [{"path": $path, "contents": $content}]')
               echo "${green}Adding $file to commit.${reset}"
             else
-              echo "::warning ::${red}File $file does not exist, skipping.${reset}"
+              echo "::warning::${red}File $file does not exist, skipping.${reset}"
             fi
           done
-
-          if [ ${#FILES_ARRAY[@]} -le 0 ]; then
-            echo "::error::No files to commit."
-            exit 1
-          fi
 
           # Add the files array to the JSON payload
           JSON_PAYLOAD=$(echo "$JSON_PAYLOAD" | jq --argjson files "$FILES_ARRAY" '.variables.files |= $files')
 
-          echo "${green}${bold}Executing GraphQL query via curl:${reset} ${yellow}curl --silent --show-error -X POST -H 'Authorization: bearer ***' -H 'Content-Type: application/json' -d '$JSON_PAYLOAD' https://api.github.com/graphql${reset}"
-
-          # Actually execute the curl command
-          if ! curl_output=$(curl --silent --show-error -X POST \
-            -H 'Authorization: token ${GITHUB_TOKEN}' \
-            -H 'Content-Type: application/json' \
+          echo "Token preview (first 5 chars): ${{ inputs.token:0:5 }}"
+          
+          # Commit the changes
+          curl_output=$(curl --silent --show-error -X POST \
+            -H "Authorization: token ${GH_AUTH_TOKEN}" \
+            -H "Content-Type: application/json" \
             -d "$JSON_PAYLOAD" \
-            https://api.github.com/graphql 2>&1); then
-              echo "::error title=Failed to commit changes.::Curl output: $curl_output"
-              exit 1
-          fi
+            https://api.github.com/graphql 2>&1)
 
+          # Check if the commit was successful 
+          if [ $? -ne 0 ] || ! echo "$curl_output" | grep -q '"commit"'; then
+            echo "::error title=Failed to commit changes.::Curl output: $curl_output"
+            exit 1
+          fi
           echo "GitHub API response: $curl_output"
         else
           echo "::warning::No files to commit."
         fi
         echo "::endgroup::"
       env:
-        REPOSITORY: ${{ github.repository }}
-        REF_NAME: ${{ github.ref_name }}
-        FILES: ${{ inputs.files }}
-        COMMIT_MESSAGE: ${{ inputs.commitMessage }}
-        GITHUB_TOKEN: ${{ inputs.token }}
+        REPOSITORY: "${{ github.repository }}"
+        REF_NAME: "${{ github.ref_name }}"
+        FILES: "${{ inputs.files }}"
+        COMMIT_MESSAGE: "${{ inputs.commitMessage }}"
+        GH_AUTH_TOKEN: "${{ inputs.token }}"
