chore: Gi bedre tilbakemelding når Code Analyser reapporterer for mange feil.

diff --git a/.github/workflows/ciStaticCodeValidation.yml b/.github/workflows/ciStaticCodeValidation.yml
--- a/.github/workflows/ciStaticCodeValidation.yml
+++ b/.github/workflows/ciStaticCodeValidation.yml
@@ -100,4 +100,10 @@ jobs:
       - name: Check the Salesforce Code Analyzer outputs to determine whether to fail
         if: ${{ !cancelled() && steps.paths.outcome == 'success' && ( steps.run-code-analyzer.outputs.exit-code > 0 || steps.run-code-analyzer.outputs.num-sev1-violations > 0 || steps.run-code-analyzer.outputs.num-violations > 10 ) }}
         shell: bash
-        run: exit 1
+        run: |
+          echo "::error title=Code Analyzer failed with exit code: ${EXIT_CODE}::Number of Sev1 violations: ${NUM_SEV1_VIOLATIONS} (max 0). Number of violations: ${NUM_VIOLATIONS} (max 10)."
+          exit 1
+        env:
+          EXIT_CODE: ${{ steps.run-code-analyzer.outputs.exit-code }}
+          NUM_SEV1_VIOLATIONS: ${{ steps.run-code-analyzer.outputs.num-sev1-violations }}
+          NUM_VIOLATIONS: ${{ steps.run-code-analyzer.outputs.num-violations }}
