Kjøre code analyzer igjennom action

diff --git a/.github/workflows/ciStaticCodeValidation.yml b/.github/workflows/ciStaticCodeValidation.yml
--- a/.github/workflows/ciStaticCodeValidation.yml
+++ b/.github/workflows/ciStaticCodeValidation.yml
@@ -75,29 +75,34 @@ jobs:
         with:
           pathToValidate: ${{ steps.paths.outputs.eslintPathsToValidate }}
 
-      # Install SF CLI
-      - uses: navikt/crm-workflows-base/.github/actions/installSF@master
-
-      - name: "Get diff sf file names"
-        id: getDiff
-        if: ${{ inputs.validateEntireRepo }} == false
-        run: |
-          mapfile -t diffedSfFiles < <(git diff --name-only --diff-filter=d HEAD~ -- src\**\*.{cls,cmp,component,css,html,js,json,page,trigger,xml})
-          json=$(jq -c -n '$ARGS.positional' --args "${diffedSfFiles[@]}")
-          echo "diffedSfFiles=$json" >> $GITHUB_OUTPUT
-
-      - name: Run Salesforce Code Analyzer
-        id: run-code-analyzer
-        uses: forcedotcom/run-code-analyzer@v1
-        if: steps.getDiff.outputs.diffedSfFiles != '[]' || inputs.validateEntireRepo
+      - name: Salesforce Code Analyzer
+        uses: navikt/sf-platform/.github/actions/runSalesforceCodeAnalyzer@main
         with:
-          run-command: run
-          run-arguments: --normalize-severity --outfile results.html --target ${{ inputs.validateEntireRepo == true && 'src' || fromJson( steps.getDiff.outputs.diffedSfFiles) }}
-          results-artifact-name: salesforce-code-analyzer-results
+          pathToValidate: ${{ steps.paths.outputs.sfCodeAnalyzerPathToValidate }}
 
-      - name: Check the Salesforce Code Analyzer outputs to determine whether to fail
-        if: |
-          steps.run-code-analyzer.outputs.exit-code > 0 ||
-          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
-          steps.run-code-analyzer.outputs.num-violations > 10
-        run: exit 1
+      # # Install SF CLI
+      # - uses: navikt/crm-workflows-base/.github/actions/installSF@master
+
+      # - name: "Get diff sf file names"
+      #   id: getDiff
+      #   if: ${{ inputs.validateEntireRepo }} == false
+      #   run: |
+      #     mapfile -t diffedSfFiles < <(git diff --name-only --diff-filter=d HEAD~ -- src\**\*.{cls,cmp,component,css,html,js,json,page,trigger,xml})
+      #     json=$(jq -c -n '$ARGS.positional' --args "${diffedSfFiles[@]}")
+      #     echo "diffedSfFiles=$json" >> $GITHUB_OUTPUT
+
+      # - name: Run Salesforce Code Analyzer
+      #   id: run-code-analyzer
+      #   uses: forcedotcom/run-code-analyzer@v1
+      #   if: steps.getDiff.outputs.diffedSfFiles != '[]' || inputs.validateEntireRepo
+      #   with:
+      #     run-command: run
+      #     run-arguments: --normalize-severity --outfile results.html --target ${{ inputs.validateEntireRepo == true && 'src' || fromJson( steps.getDiff.outputs.diffedSfFiles) }}
+      #     results-artifact-name: salesforce-code-analyzer-results
+
+      # - name: Check the Salesforce Code Analyzer outputs to determine whether to fail
+      #   if: |
+      #     steps.run-code-analyzer.outputs.exit-code > 0 ||
+      #     steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
+      #     steps.run-code-analyzer.outputs.num-violations > 10
+      #   run: exit 1
